input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  if [project] == "atlas" {
    mutate { add_field => { "[@metadata][target_index]" => "atlas-symfony-json-%{+YYYY.MM.dd}" } }
  }

  mutate {
    remove_field => ["host", "agent"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
