input {
  beats {
    port => 5045
  }
}

filter {
  json {
    source => "message"
  }

  if [project] == "atlas_countries" {
    if [log_type] == "cli" {
      mutate { add_field => { "[@metadata][target_index]" => "atlas-countries-symfony-cli-%{+YYYY.MM.dd}" } }
    } else {
      mutate { add_field => { "[@metadata][target_index]" => "atlas-countries-symfony-json-%{+YYYY.MM.dd}" } }
    }
  }

  mutate {
    remove_field => ["host", "agent"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
